affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: intent
          operator: In
          values:
          - intent_value

annotations:
  sidecar.istio.io/inject: "false"
